services:
  db:
    image: postgres
    restart: always
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: freehoot
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: freehoot_development
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
