#!/bin/bash
set -e

/opt/homebrew/opt/libpq/bin/psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER '$POSTGRES_USER' WITH PASSWORD '$POSTGRES_PASSWORD';
	CREATE DATABASE '${POSTGRES_USER}_development';
	GRANT ALL PRIVILEGES ON DATABASE '${POSTGRES_USER}_development' TO '$POSTGRES_USER';
EOSQL
